### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by kreezxil** [john01dav/ServerForge#3]
is no longer available the one provided by breezyboy.

Is there anything build for 1.8 which is at b1450 now :)

**Comment by john01dav** [comment]
There is no 1.8 build available of ServerForge.

**Comment by tjwmagic** [comment]
I went to the Downloads spot to find the ServerForge mod file for 1.7.10, (https://github.com/john01dav/ServerForge/wiki/Downloads) and could not get the file. It shows the link, (http://ci.breezeyboy.com/job/ServerForge/) but that takes you to a "this webpage is not available." Could I get a direct link to the file for 1.7.10?

**Comment by john01dav** [comment]
You need to clone the repository then build it yourself. There are no precompiled jars available.

**Comment by tjwmagic** [comment]
Ok, how do you build the repository?

**Comment by john01dav** [comment]
On Linux, run `./gradelw build` in the repository's root. It's very similar for other OS'es, please let me know if you can't figure it out.

**Comment by tjwmagic** [comment]
For windows you open the command prompt to that folder, then type the command 'gradelw.bat build' correct?

**Comment by john01dav** [comment]
It's been literally years since I last used Windows for anything useful, although that does sound about right.

Unless something goes drastically wrong, you can always just re-clone the repository.

**Comment by john01dav** [comment]
It will be located at `/path/to/ServerForge/build/libs/ServerForge-PRE-ALPHA.jar` once the build completes.

**Comment by tjwmagic** [comment]
So I just tried that command and got a Build Failed. It says it is with the JDK so I am going to troubleshot that. If I run into more problems I'll come to you. Thank you so much for your time!

**Comment by john01dav** [comment]
No problem. Also, your error sounds like you don't have a JDK installed (you need one to build really anything that is Java related).

**Comment by tjwmagic** [comment]
Hey so I got ServerForge installed. Thank you for the help on that. Now I got a new question. Is there any already made plugins and if so is there a location to them? Or do I have to make the plugins? Thanks!

**Comment by john01dav** [comment]
You'll need to make the plugins. Also, if you're done with this ticket, please close it.
